---
kind: pipeline
name: gitnex-ci-test

steps:

  - name: test
    image: nextcloudci/android:android-49
    commands:
      - ./gradlew test

trigger:
  event:
    - pull_request

---
kind: pipeline
name: gitnex-ci-build

steps:

  - name: build
    image: nextcloudci/android:android-49
    commands:
      - ./gradlew build

  - name: sign
    image: nextcloudci/android:android-49
    environment:
      TOKEN:
        from_secret: BOT_TOKEN
      KS_PASS:
        from_secret: KS_PASS
      KEY_PASS:
        from_secret: KEY_PASS
      OUTPUT: signed.apk
      GITEA: https://gitea.com
      KS_FILE: ci_keystore.jks
      KS_REPO:
        from_secret: KS_REPO
    commands:
      - ./scripts/sign-build.sh

  - name: publish
    image: nextcloudci/android:android-49
    environment:
      NC_TOKEN:
        from_secret: NC_TOKEN
    commands:
      - ./scripts/upload-build.sh

trigger:
  event:
    - push
  branch:
    - master