
kind: pipeline
name: testing

steps:

  - name: test
    image: nextcloudci/android:android-49
    commands:
      - ./gradlew test

  - name: build
    image: nextcloudci/android:android-49
    commands:
      - ./gradlew build

trigger:
  branch:
    - master

  event:
    - push
    - pull_request
