stages:
  - test
  - build
  - sign
  - publish

test:
  image: nextcloudci/android:android-49
  stage: test
  script:
    - ./gradlew test

build:
  image: nextcloudci/android:android-49
  stage: build
  only:
    - master
  script:
    - ./gradlew build

sign:
  image: nextcloudci/android:android-49
  stage: sign
  only:
    - master
  variables:
    OUTPUT: "signed.apk"
    GITEA: "https://gitea.com"
    KS_FILE: "ci_keystore.jks"
  script:
    - ./scripts/sign-build.sh

publish:
  image: byrnedo/alpine-curl
  stage: publish
  only:
    - master
  variables:
    WEBDAV_USERNAME: "GitNexBot"
    PLUGIN_FILE: "signed.apk"
    PLUGIN_DESTINATION: "https://cloud.swatian.com/remote.php/dav/files/GitNexBot/GitNex-Builds/latest.apk"
  script:
    - curl -T $PLUGIN_FILE -u $WEBDAV_USERNAME:$WEBDAV_PASSWORD $PLUGIN_DESTINATION
