pipeline:
  author-header:
    image: qwerty287/woodpecker-regex-check
    group: check
    settings:
      pattern: "*.java"
      regex: " \\\\* \\\\@author [\\\\S\\\\s]+"
      must_contain: true

  style-diff-test:
    image: ubuntu:20.04
    group: check
    commands:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -yq git=1:2.25.1-1ubuntu3.5 wget=1.20.3-1ubuntu2 libfreetype6=2.10.1-2ubuntu0.2 xorg=1:7.7+19ubuntu14
      - wget --no-verbose -O /tmp/idea.tar.gz https://download.jetbrains.com/idea/ideaIC-2022.1.3.tar.gz
      - cd /opt
      - tar xzf /tmp/idea.tar.gz
      - mv /opt/idea* /opt/idea
      - /opt/idea/bin/idea.sh format -s "$(pwd)/.idea/codeStyles/Project.xml" -m "*" -r .
      - git diff

  style:
    image: qwerty287/woodpecker-intellij-formatter
    group: check
    settings:
      file_pattern: "*.java"
      path: "app/"
