pipeline:
  author-header:
    image: qwerty287/woodpecker-regex-check
    settings:
      pattern: "*.java"
      regex: " \\\\* \\\\@author [\\\\S\\\\s]+"
      must_contain: true

  style:
    image: qwerty287/woodpecker-intellij-formatter
    settings:
      file_pattern: "*.java"
      path: "app/"
